### ISSUE TITLE
[fedora 24] ImportError: cannot import name convert_error

### ISSUE THREAD

**Issue by gregsheremeta** [keithgg/puddletag#319]
installed with 'sudo dnf install puddletag' on Fedora 24 and it will not start:

$ puddletag
Traceback (most recent call last):
  File "/usr/bin/puddletag", line 328, in <module>
    migrate_settings()
  File "/usr/bin/puddletag", line 86, in migrate_settings
    _migrate_action_shortcuts()
  File "/usr/bin/puddletag", line 92, in _migrate_action_shortcuts
    from puddlestuff.puddleobjects import PuddleConfig
  File "/usr/lib/python2.7/site-packages/puddlestuff/puddleobjects.py", line 16, in <module>
    import audioinfo
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/__init__.py", line 104, in <module>
    import id3, vorbis, apev2, mp4
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/id3.py", line 6, in <module>
    import mutagen, mutagen.id3 as id3, mutagen.mp3
  File "/usr/lib/python2.7/site-packages/mutagen/mp3/__init__.py", line 14, in <module>
    from mutagen._util import MutagenError, enum, BitReader, BitReaderError, \
ImportError: cannot import name convert_error

$ rpm -q python-mutagen
python-mutagen-1.32-1.fc24.noarch

**Comment by keithgg** [comment]
The version built in Fedora is too old. The new version of mutagen made some changes that brokes some imports, but is fixed in master. 

I should really make a release.
