### ISSUE TITLE
UnicodeEncodeError when formatting filenames

### ISSUE THREAD

**Issue by ronno** [keithgg/puddletag#328]
I keep running into an error when formatting filenames that contain unicode characters.
Here's the full trace:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/puddlestuff/mainwin/funcs.py", line 506, in update_status
    newfilename = functions.move(tag, pattern, tag, state=state.copy())
  File "/usr/lib/python2.7/site-packages/puddlestuff/functions.py", line 499, in move
    fn = tag_to_filename(p_pattern, m_tags, r_tags, ext, state)
  File "/usr/lib/python2.7/site-packages/puddlestuff/functions.py", line 455, in tag_to_filename
    new_fn = encode_fn(path_join(*new_dirs))
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/util.py", line 176, in encode_fn
    return filename.encode(FS_ENC)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-32: ordinal not in range(128)
```

**Comment by keithgg** [comment]
Problem is most likely your filesystem. If you save a file with a non-ascii filename outside puddletag, what happens?
