### ISSUE TITLE
Cannot display M4A songs or tags: "TypeError: coercing to Unicode" error

### ISSUE THREAD

**Issue by nick-s-b** [keithgg/puddletag#339]
Hi all,

Last time I used Puddletag was over a month ago and haven't had any issues. When I tried using it today, it would start just fine but it wouldn't display any folders and the right side of the puddletag window would just remain empty if I tried opening folders with M4A files. It displays MP3 files and tags just fine, however. After running it from terminal, I noticed a slew of errors that look like this:

```
$ puddletag
puddletag Version: 1.2.0
Locale: en_US
Object::disconnect: Unexpected null parameter
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
An error occured.
/Volumes/Music/Tokio Hotel - Dream Machine (2017)/04 What If.m4a
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/puddlestuff/puddleobjects.py", line 675, in gettag
    return audioinfo.Tag(f)
  File "/usr/lib/python2.7/site-packages/puddlestuff/tagmodel.py", line 298, in ReplacementTag
    return extensions[ext][1](filename)
  File "/usr/lib/python2.7/site-packages/puddlestuff/tagmodel.py", line 151, in __init__
    super(ModelTag, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/mp4.py", line 190, in __init__
    util.MockTag.__init__(self, filename)
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/util.py", line 663, in __init__
    self.link(filename)
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/mp4.py", line 366, in link
    isinstance(v, unicode) else v for v in audio[key]]
TypeError: coercing to Unicode: need string or buffer, int found
An error occured.
/Volumes/Music/Tokio Hotel - Dream Machine (2017)/03 Easy.m4a
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/puddlestuff/puddleobjects.py", line 675, in gettag
    return audioinfo.Tag(f)
  File "/usr/lib/python2.7/site-packages/puddlestuff/tagmodel.py", line 298, in ReplacementTag
    return extensions[ext][1](filename)
  File "/usr/lib/python2.7/site-packages/puddlestuff/tagmodel.py", line 151, in __init__
    super(ModelTag, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/mp4.py", line 190, in __init__
    util.MockTag.__init__(self, filename)
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/util.py", line 663, in __init__
    self.link(filename)
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/mp4.py", line 366, in link
    isinstance(v, unicode) else v for v in audio[key]]
TypeError: coercing to Unicode: need string or buffer, int found
An error occured.
```

I'm using Arch Linux and puddletag version is 1.2.0 , PyQt 4.12, Mutagen 1.37, Pyparsing 2.1.10 and Qt 4.8.7.

Any suggestions or help is much appreciated. Thanks!

**Comment by keithgg** [comment]
Thanks for letting me know. Will include in the next release.

**Comment by uklotzde** [comment]
python2-mutagen has been upgraded from 1.36.2 to 1.37 in Fedora 25 just recently. This makes puddletag 1.20 unusable for almost all .m4a files.

I've manually replaced /usr/lib/python2.7/site-packages/puddlestuff/audioinfo/mp4.py with this patched version, but that didn't help either:
```
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/mp4.py", line 372, in link
    field_value.append(unicode(v, 'utf8'))
TypeError: coercing to Unicode: need string or buffer, int found
```
The code in the final else-branch is identical with that in the first if-branch.
