### ISSUE TITLE
[Issue|bug] - No longer able to open puddletag

### ISSUE THREAD

**Issue by dbzlotrfan** [keithgg/puddletag#350]
Basically I was using puddletag, listening to music, music froze the computer, rebooted and now puddletag won't start, If I try with a terminal I get:

dlf@dlf:~$ puddletag
puddletag Version: 1.2.0
Locale: en_US
Traceback (most recent call last):
  File "/usr/bin/puddletag", line 350, in <module>
    win = MainWin()
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddletag.py", line 370, in __init__
    self.restoreSettings()
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddletag.py", line 637, in restoreSettings
    status['genres'] = genres.load_genres()
  File "/usr/lib/python2.7/dist-packages/puddlestuff/genres.py", line 15, in load_genres
    open(filepath, 'r').readlines()]
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 1: invalid start byte

Running Linux Mint 18.1 (With cinnamon as the DE), I have run **sudo apt-get purge puddletag** and afterwards run **sudo apt-get install puddletag** and I still run into the same issue. Why?

**Comment by keithgg** [comment]
Not sure why it's bogging out, but if you delete the file in ~/.config/puddletag/genres I think it'll start up.
