### ISSUE TITLE
Causes mate-maximus to end

### ISSUE THREAD

**Issue by thwaller** [keithgg/puddletag#370]
After opening Puddletag, at some point, mate-maximus stops running. There is no error given, no message or anything. It just disappears from the running processes and needs to be restarted. I have not yet found out which specific action(s) cause it, but I can say that it is not opening the application, it happens whilst in use somewhere. I can restart mate-maximus easily and without issue, but only when I close Puddletag does it stay running.

I am running Ubuntu MATE 17.04 with Puddletag 1.2.0

**Comment by thwaller** [comment]
I can confirm the issue is for sure something with Puddletag. Although it only happened once (just now), upon opening Puddletag (which opened maximized), mate-panel failed and was no longer displayed. Same as prior, there is no error or notification seen, it just disappeared. Puddletag continued to function just fine, as did the other open applications.

On the above (first) issue, it appears it is linked to using the Extended Tags window. There are also display quarks there when using a pulldown on the values.

**Comment by thwaller** [comment]
Here is a portion of terminal output that is output during this error/issue. I took a bit before and after the Puddletag mention, I hope it is enough.

TypeError: <lambda>() takes exactly 2 arguments (4 given)
TypeError: <lambda>() takes exactly 2 arguments (4 given)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
TypeError: <lambda>() takes exactly 2 arguments (4 given)
Unhandled exception in thread started by <function urlopen at 0x7fd3688c8e60>
Traceback (most recent call last):
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 414, in open
    req = Request(fullurl, data)
  File "/usr/lib/python2.7/urllib2.py", line 230, in __init__
    self.__original, self.__fragment = splittag(self.__original)
puddletag Version: 1.2.0
Locale: en_US

(python:24813): GVFS-RemoteVolumeMonitor-WARNING **: remote volume monitor with dbus name org.gtk.vfs.GoaVolumeMonitor is not supported

(mate-maximus:22645): Gdk-ERROR **: The program 'mate-maximus' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 3234 error_code 3 request_code 20 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[25726:25767:0908/222005.627471:ERROR:nss_util.cc(747)] After loading Root Certs, loaded==false: NSS error code: -8018
Created new window in existing browser session.`

**Comment by keithgg** [comment]
Hi @thwaller 

Thanks for the report. Does it just happen with mate-maximus? What happens if you try it a different desktop environment (like plain GNOME)?

**Comment by thwaller** [comment]
I booted into GNOME (not on Wayland) and it was slightly different. I was not able to maximize it at all. It took up approx 1/2 of the screen, top-to-bottom in full and left to about mid-screen. I was not given the option to maximize further, just close or minimize.

Also, the other issue I reported was the same in GNOME as it is in MATE.

**Comment by thwaller** [comment]
To rule out a bad deb, I have tried this via downloading the files directly and running ./puddletag from command with the fresh files. Nothing changed in the issue reported here. I saw that you are no longer providing deb files, so I wanted to rule out any issues on that side as I have seen that before on other softwares.

**Comment by thwaller** [comment]
During the file testing, I have found that this issue seems to be on AAC M4A files only. This does not happen while opening ALAC files during testing on this issue:
https://github.com/keithgg/puddletag/issues/374
I also confirmed this does not happen with MP3 files

**Comment by thwaller** [comment]
@keithgg - I wanted to add some more misc stuff since I reported 2 issues and others have for some small oddities as well. Since I cannot use Puddletag at this time, and I am not a fan of using Wine for MP3Tag, I have been using Kid3. What I have noticed is while uploading to Google Play Music, I find that the files tagged with Kid3 are better recognized by Google than those I had tagged with Puddletag (and same goes for MP3Tag as well. Things like the release date, total release tracks, etc... details like this prior to my using Kid3 would sometimes be missing, although I could see this data in the tags on my files and in my local player softwares. Kid3 tagged files have not had this issue at all to the best of my recollection.

This data, this one and my other reports here, come form my usage over the past 6 months or so. I have tagged approx 20k songs (according to Google Play Music that is what I uploaded) and about half of those were Puddletag done whilst the other half is about 80% Kid3 and 20% MP3Tag (via Wine). Prior to this mentioned batch, all my tagging was done via MP3Tag on Windows, so those files have little use here for comparison. I share this to show only that my reports here on this come from a significant sample vs only a few songs or releases. I have all set to use v2.4 (MP3) only with UTF8, so that is a common for all.

**Comment by keithgg** [comment]
@thwaller thanks for the reports. Sorry for making it seem like you're speaking into a void. When I have a block of time available I'll look into this more.

>  I have noticed is while uploading to Google Play Music, I find that the files tagged with Kid3 are better recognized by Google than those I had tagged with Puddletag (and same goes for MP3Tag as well. Things like the release date, total release tracks, etc... details like this prior to my using Kid3 would sometimes be missing, although I could see this data in the tags on my files and in my local player softwares. Kid3 tagged files have not had this issue at all to the best of my recollection.

Is this specific to mp4/aac files or over any file tagged with puddletag?

**Comment by thwaller** [comment]
No problem. Ahh, I failed to include that part, sorry for lack of clarity. This is in reference to MP3 files and not MP4. As time has moved and I have done more files, I am wondering if this specific issue is more on Google and its ability to read tags, specifically 2.3 vs 2.4 and exactly which atom holds data. The most common field where this issue appears if the date. The result is after upload, the files do not appear in Google Music with a date, and it requires manual adding. Next come things like total tracks and disc numbers. That is what leads me to believe it is a destination reading issue as things like disc number can go in more than one place. MP4 files (for this meaning AAC encoded audio in M4A container) are most always fine, which I am assuming is due to a more constant standard given what is stated here.

I came to this assumption because I noticed that in PuddleTag, if I set 2.4 as the default, it will convert all to 2.4 from 2.3 on a save, whereas in Kid3, it will leave as 2.3 unless I convert the tags, and will only add new as 2.4, 2.4 being set as default. Due to this, I believe what may be happening is that resulting files from PuddleTag are having 2.4 meta whilst Kid3 would have had 2.3 meta. I have not uploaded MP3 source in a while, so I cannot yet confirm this. It is just an observation at this point.
