### ISSUE TITLE
Puddletag is now broken after updates - will not load files

### ISSUE THREAD

**Issue by thwaller** [keithgg/puddletag#374]
Puddletag no longer displays a loaded directory after running the latest Ubuntu updates via Package Manager. It will provide the popup that comes while it loads the files normally, but after, nothing is displayed. I cannot do a select all, nothing happens. I was looking for maybe an issue with theme where it was there but not visible to the eye sort of thing. Prior to the updates, it was working fine, except for the bug I reported prior on it causing mate-maximus to crash. That also still happens with this and has not changed.

I am running:
Release 17.04 (Zesty Zapus) 64-bit
Kernel Linux 4.10.0-36-generic x86_64
MATE 1.18.0
All updates via package manager up-to-date through Sept 28th.

PLease ask what other information is needed, I know this sort of issue will require more data. I will be happy to provide and test in order to resolve.

**Comment by keithgg** [comment]
Hi @thwaller 

Can you start puddletag from the console and check if there's any output?

Can you also provide the PyQt and Qt versions (you can get the from the "Help -> About" menu.

**Comment by thwaller** [comment]
xxxxxx:~$ puddletag
puddletag Version: 1.2.0
Locale: en_US

(python:28413): GVFS-RemoteVolumeMonitor-WARNING **: remote volume monitor with dbus name org.gtk.vfs.GoaVolumeMonitor is not supported
An error occured.
/home/xxxxxx/SLAVA KAMINSKA - Хорошо - Single - (2017)/01 - SLAVA KAMINSKA - Хорошо.m4a
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddleobjects.py", line 675, in gettag
    return audioinfo.Tag(f)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/tagmodel.py", line 298, in ReplacementTag
    return extensions[ext][1](filename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/tagmodel.py", line 151, in __init__
    super(ModelTag, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/mp4.py", line 190, in __init__
    util.MockTag.__init__(self, filename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/util.py", line 663, in __init__
    self.link(filename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/mp4.py", line 366, in link
    isinstance(v, unicode) else v for v in audio[key]]
TypeError: coercing to Unicode: need string or buffer, int found
xxxxxx:~$

**Comment by thwaller** [comment]
This program uses Qt version 4.8.7.
PyQt  4.11.4
Mutagen  1.38
Pyparsing 2.1.10

**Comment by thwaller** [comment]
To rule out a bad deb, I have tried this via downloading the files directly and running ./puddletag from command with the fresh files. Nothing changed in the issue reported here. I saw that you are no longer providing deb files, so I wanted to rule out any issues on that side as I have seen that before on other softwares.

**Comment by thwaller** [comment]
In addition to all working fine with MP3 files as seen in the above referenced issue, I have also now tested M4A container files containing ALAC encoded audio. Those files also work just fine.
