### ISSUE TITLE
Puddletag will not read some files that it had previously

### ISSUE THREAD

**Issue by oshunluvr** [keithgg/puddletag#407]
I am using Puddletag 1.20 on KDEneon (Ubuntu 16.04 with the latest Plasma 5/QT5)

Many older videos in my collection will no longer load into Puddletag. I haven't gone through all of them, but these appear to be mostly 3 years old or older. I would have created and tagged most of them with Puddletag using Kubuntu 14.04

I launched Puddletag form Konsole and got this error output when a file wasn't read;
```
An error occured.
/shared/Videos/Somevideo.mp4
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddleobjects.py", line 675, in gettag
    return audioinfo.Tag(f)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/tagmodel.py", line 298, in ReplacementTag
    return extensions[ext][1](filename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/tagmodel.py", line 151, in __init__
    super(ModelTag, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/mp4.py", line 190, in __init__
    util.MockTag.__init__(self, filename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/util.py", line 663, in __init__
    self.link(filename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/mp4.py", line 366, in link
    isinstance(v, unicode) else v for v in audio[key]]
TypeError: coercing to Unicode: need string or buffer, int found
```
It's the same for every file that gets skipped. The "Wait" window opens and counts through the files in the folders, but none are listed in the main window afterward.

These are all mp4 files and no other application I've tried has any trouble and I edited one of the tags using another program to see if re-writing the tag would fix it but it did not.

I did recently upgrade my server to Ubuntu 18.04, but it's headless and I access the files via NFS.

I don't know if this is a tag issue, a QT issue, or what but it seems odd that some files are read while others are not.

**Comment by oshunluvr** [comment]
It looks like the older files have many more tags then the newer ones, so it's clearly a tag issue. There must be a tag or two that are causing the issue. The newer files only have the basic tags (title, episodes, etc) where the older ones have things like descriptions, cover art, etc.

**Comment by krys-barry** [comment]
I have also encountered this. Without making much effort to understand what was happening I changed isinstance(v, unicode) to isinstance(str(v), unicode). The files that were failing now load successfully.

**Comment by czgirb** [comment]
> I have also encountered this. Without making much effort to understand what was happening I changed isinstance(v, unicode) to isinstance(str(v), unicode). The files that were failing now load successfully.

changed isinstance(v, unicode) to isinstance(str(v), unicode)
how to do it? please guide me ...
thank you

**Comment by ruanom** [comment]
> > I have also encountered this. Without making much effort to understand what was happening I changed isinstance(v, unicode) to isinstance(str(v), unicode). The files that were failing now load successfully.
> 
> ... **changed isinstance(v, unicode) to isinstance(str(v), unicode)** ...
> how to do it? please guide me ...
> thank you

I am having exactly the same problem. krys-barry, can you explain where isinstance(v, unicode) to isinstance(str(v), unicode) can be found?

Thanks!

**Comment by oshunluvr** [comment]
This issue still exists

**Comment by hsandt** [comment]
If you have issues specifically with mp4, m4a and aac it may be the same as https://github.com/puddletag/puddletag/issues/414
