### ISSUE TITLE
Puddletag freezes upon running an autonumbering function

### ISSUE THREAD

**Issue by ranperry** [keithgg/puddletag#429]
Using the latest version on Mint 19. Ways to reproduce:

1. Start puddle tag
2. Select a directory
3. Click on "Functions"
4. Chose "Autonumbering"
5. Chose "discnumber" as the tag you want to use.
6. Click "OK"

Expected result:

Puddletag will insert values into the "discnumber" tag

Actual result:

A small window appears with "Please wait" message. Nothing will happen until the user clicks "Cancel". No tags will be written.

Let me know if you need further info.

**Comment by ranperry** [comment]
Added the following output:

puddletag Version: 2.0.1
qt5ct: using qt5ct plugin
Locale: en_CA
qt5ct: D-Bus global menu: no
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 895, in threadfunc
    temp = next(f)
  File "/usr/lib/python3/dist-packages/puddlestuff/puddletag.py", line 737, in func
    for row, f in zip(rows, tagiter):
  File "/usr/lib/python3/dist-packages/puddlestuff/mainwin/funcs.py", line 457, in tagiter
    val = function(rowtags.get(field, ''), rowtags, state, r_tags=f)
  File "/usr/lib/python3/dist-packages/puddlestuff/findfunc.py", line 873, in runFunction
    return func(**topass)
  File "/usr/lib/python3/dist-packages/puddlestuff/functions.py", line 102, in autonumbering
    tracknum = state['autonumbering'][index]
KeyError: 2
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_puddletag.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 895, in threadfunc
    temp = next(f)
  File "/usr/lib/python3/dist-packages/puddlestuff/puddletag.py", line 737, in func
    for row, f in zip(rows, tagiter):
  File "/usr/lib/python3/dist-packages/puddlestuff/mainwin/funcs.py", line 457, in tagiter
    val = function(rowtags.get(field, ''), rowtags, state, r_tags=f)
  File "/usr/lib/python3/dist-packages/puddlestuff/findfunc.py", line 873, in runFunction
    return func(**topass)
  File "/usr/lib/python3/dist-packages/puddlestuff/functions.py", line 102, in autonumbering
    tracknum = state['autonumbering'][index]
KeyError: 2

**Comment by JELittleton** [comment]
I experienced this issue while attempting to autonumber a 200 track podcast. The "Autonumbering Function" stalled at writing the first record and never proceeded any further. I was forced to cancel the function to continue working in Puddletag.

I later discovered it is possible to create an "Action" to successfully perform autonumbering of tracks by creating an "Action" based on the faulty "Autonumbering Function".

1. From the toolbar menu select: Actions > Actions.
2. Add a new Action by selecting the green plus "+" button.
3. Enter a title for the new action: "Numbering".
4. Add an action to the new "Action: Numbering" by selecting the green plus "+" button again.
5. Select "Autonumbering" from the drop down menu bar at top of window.
6. Select "track" from the "field" drop down menu below the "Autonumbering" menu (above).
7. Select "OK" to add the "Autonumbering" function to the new "Numbering" action just created above.
8. Review the parameters of the "Autonumbering" function just added the new "Numbering" action just created above.
9. If the parameters appear correct, select "OK" to create the new "Numbering" action.
Note: Changing some of the function numbering parameters is ineffective when applied. No idea why. Caveat: YMMV.

To use the new action: 

1. Select/highlight all of the desired cells in the "Track" column for each track to be numbered.
2. From the toolbar menu select: Actions > Actions.
3. Select (enter a check mark for) the newly created action "Numbering".
4. Select "OK" to run the "Numbering" action.
