### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by HanaO00** [keithgg/puddletag#435]
Hello, i have this error when i launch puddletag : 

`puddletag 
puddletag Version: 1.2.0
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/usr/bin/puddletag", line 317, in <module>
    init(options, app)
  File "/usr/bin/puddletag", line 169, in init
    load_language(qapp, options.langfile)
  File "/usr/bin/puddletag", line 204, in load_language
    lang = cparser.get('main', 'lang', u'auto')
  File "/usr/lib/python2.7/site-packages/puddlestuff/puddleobjects.py", line 233, in get
    return int(value)
ValueError: invalid literal for int() with base 10: 'fr'
`

**Comment by cmorgenstern** [comment]
Experiencing the same issue with a pyqt5 branch build. Built on Arch Linux from the following [PKGBUILD](https://gist.github.com/cmorgenstern/663c6ae9dee33216e24ca6ea7b3c5ad6):

Result:
```
[user@host ~]$ puddletag
puddletag Version: 1.2.0
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/usr/bin/puddletag", line 317, in <module>
    init(options, app)
  File "/usr/bin/puddletag", line 169, in init
    load_language(qapp, options.langfile)
  File "/usr/bin/puddletag", line 204, in load_language
    lang = cparser.get('main', 'lang', u'auto')
  File "/usr/lib/python2.7/site-packages/puddlestuff/puddleobjects.py", line 233, in get
    return int(value)
ValueError: invalid literal for int() with base 10: 'auto'
```

I was able to work around it by commenting the following:
```
--- /usr/lib/python2.7/site-packages/puddlestuff/puddleobjects.py	2019-04-29 17:13:59.580513442 +1200
+++ /usr/lib/python2.7/site-packages/puddlestuff/puddleobjects.py.bak	2019-04-29 16:59:21.579046362 +1200
@@ -228,11 +228,11 @@
             if value is True or value == 'True':
                 return True
             return False
-#        elif getint or isinstance(default, (long,int)):
-#            try:
-#                return int(value)
-#            except TypeError:
-#                return map(int, value)
+        elif getint or isinstance(default, (long,int)):
+            try:
+                return int(value)
+            except TypeError:
+                return map(int, value)
         else:
             if value is None:
                 return default
```
At that point, though, I started experiencing the same issue reported [here](https://github.com/keithgg/puddletag/issues/432).

Other potentially relevant information:
`local/qt5-base 5.12.3-2 (qt qt5)`
`Linux 5.0.9-arch1-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux`
`Python 2.7.16`

I'm still very much a novice as far as working with Python, so if there is a better solution than commenting out the offending lines, please feel free to share. Thank you!
