### ISSUE TITLE
Extended tags not working

### ISSUE THREAD

**Issue by JustPerfection** [keithgg/puddletag#443]
When I select a file and click on extended tags these errors appear on terminal:

`Traceback (most recent call last):
  File "/home/ice/Applications/puddletag/source/puddlestuff/mainwin/funcs.py", line 169, in extended_tags
    win = helperwin.ExTags(files = status['selectedfiles'], parent=parent)
  File "/home/ice/Applications/puddletag/source/puddlestuff/helperwin.py", line 713, in __init__
    self.loadFiles(files)
  File "/home/ice/Applications/puddletag/source/puddlestuff/helperwin.py", line 894, in loadFiles
    italics = set(audios[0].equal_fields())
AttributeError: 'Tag' object has no attribute 'equal_fields'
[1]+  Killed                  ./puddletag
`

Ubuntu 18.04.3 (GNOME)

**Comment by asmol82** [comment]
Have the same problem. Have anyone solved it? LinuxMint 19.02 (Cinnamon) 64-bit.

**Comment by JustPerfection** [comment]
open puddlestuff/helperwin.py and find these lines:
`
italics = set(audios[0].equal_fields())
            self.piclabel.currentFile = audios[0]
            self.piclabel.filePattern = self.status['cover_pattern']

            for audio in audios[1:]:
                previews = previews.intersection(audio.preview)
                italics = italics.intersection(audio.equal_fields())

            row = 0

            for field, values in common.iteritems():
                if field in italics:
                    preview = UNCHANGED
                #field in italics => field in previews.
                elif field in previews:
                    preview = BOLD
                else:
                    preview = UNCHANGED
`
change it to this (see where did I use # to comment):
`
#italics = set(audios[0].equal_fields())
            self.piclabel.currentFile = audios[0]
            self.piclabel.filePattern = self.status['cover_pattern']

            for audio in audios[1:]:
                previews = previews.intersection(audio.preview)
                #italics = italics.intersection(audio.equal_fields())

            row = 0

            for field, values in common.iteritems():
                #if field in italics:
                    #preview = UNCHANGED
                #field in italics => field in previews.
                #elif field in previews:
                    #preview = BOLD
                #else:
                preview = UNCHANGED
`
Fixed
